# Generated by Django 3.0.4 on 2020-04-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_user_data_dp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='bio',
            field=models.TextField(default=models.CharField(default='none', max_length=20), max_length=40),
        ),
        migrations.AddField(
            model_name='user_data',
            name='friends_name',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='user_data',
            name='friends_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_data',
            name='name',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='user_data',
            name='uname',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='dp',
            field=models.ImageField(upload_to='DP'),
        ),
    ]
