# Generated by Django 3.0.4 on 2020-04-04 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_auto_20200404_1418'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Profile',
        ),
    ]
